### PR TITLE
Make implementer tools hidden by default

### PR DESCRIPTION
**Pull request by donaldkibet**
### What does this PR do?

It hides the implementer rectangular button at the bottom right corner of the window for non-admin users

### Description of Task completed 

Hide the implementer tools to non-admin users by checking users' privilege to determine whether to show it or hide it.

### Screenshoots

tools

﻿

### CODE REVIEW

**Comment by brandones** [comment]
@donaldkibet , thank you for this! However, I think what we actually want is to have something that always shows just for System Administrators (i.e. based on that privilege). Eventually I think it would ideally be in the navbar (probably as an extension), but for now I think it would be fine just to wrap this button in a privilege check. Does that make sense?

**Comment by donaldkibet** [comment]
> @donaldkibet , thank you for this! However, I think what we actually want is to have something that always shows just for System Administrators (i.e. based on that privilege). Eventually I think it would ideally be in the navbar (probably as an extension), but for now I think it would be fine just to wrap this button in a privilege check. Does that make sense?

Sure :+1:

**Review by brandones — APPROVED** [review]
If that's all it took, looks good to me! Thanks for this!

**Review by FlorianRappl — APPROVED** [review]
LGTM!

**Pull request merged**
